import type { Property } from './types';

export const properties: Property[] = [
  {
    id: '1',
    title: 'Modern 3BHK Apartment in Sector 1',
    type: 'Apartment',
    transaction: 'Sell',
    price: 4500000,
    location: 'Sector 1, Pithampur',
    area: 1500,
    bedrooms: 3,
    bathrooms: 2,
    description: 'A beautiful and modern apartment with all amenities. Located in the heart of the city, with easy access to schools, hospitals, and markets.',
    images: [
      'https://placehold.co/800x500.png',
      'https://placehold.co/800x500.png',
      'https://placehold.co/800x500.png',
    ],
    amenities: ['Parking', 'Power Backup', 'Lift', 'Security'],
    sellerName: 'Ramesh Kumar',
    sellerPhone: '9876543210',
    featured: true,
  },
  {
    id: '2',
    title: 'Spacious 2BHK for Rent',
    type: 'Apartment',
    transaction: 'Rent',
    price: 12000,
    location: 'Mhow Road, Pithampur',
    area: 1200,
    bedrooms: 2,
    bathrooms: 2,
    description: 'Well-maintained 2BHK flat available for rent in a prime location. Ideal for families.',
    images: [
      'https://placehold.co/800x500.png',
    ],
    amenities: ['Parking', 'Water Supply'],
    sellerName: 'Suresh Singh',
    sellerPhone: '9876543211',
    featured: false,
  },
  {
    id: '3',
    title: 'Residential Plot for Sale',
    type: 'Plot',
    transaction: 'Sell',
    price: 2000000,
    location: 'Special Economic Zone (SEZ), Pithampur',
    area: 2000,
    bedrooms: 0,
    bathrooms: 0,
    description: 'Excellent investment opportunity. Residential plot in a rapidly developing area.',
    images: [
      'https://placehold.co/800x500.png',
    ],
    amenities: ['Gated Community', 'Road'],
    sellerName: 'Anjali Sharma',
    sellerPhone: '9876543212',
    featured: true,
  },
  {
    id: '4',
    title: 'Independent House with Garden',
    type: 'House',
    transaction: 'Sell',
    price: 7500000,
    location: 'Sector 3, Pithampur',
    area: 2500,
    bedrooms: 4,
    bathrooms: 3,
    description: 'A beautiful independent house with a lush green garden. Perfect for a large family looking for a peaceful environment.',
    images: [
      'https://placehold.co/800x500.png',
      'https://placehold.co/800x500.png',
    ],
    amenities: ['Parking', 'Garden', 'Servant Quarters'],
    sellerName: 'Vikram Batra',
    sellerPhone: '9876543213',
    featured: false,
  },
  {
    id: '5',
    title: 'Commercial Shop on Main Road',
    type: 'Shop',
    transaction: 'Rent',
    price: 25000,
    location: 'Indore Road, Pithampur',
    area: 800,
    bedrooms: 0,
    bathrooms: 1,
    description: 'Prime commercial shop space available for rent on the busy main road. High footfall area.',
    images: [
      'https://placehold.co/800x500.png',
    ],
    amenities: ['Main Road Facing', 'Parking'],
    sellerName: 'Priya Jain',
    sellerPhone: '9876543214',
    featured: true,
  },
  {
    id: '6',
    title: 'Luxury 4BHK Villa',
    type: 'House',
    transaction: 'Sell',
    price: 12000000,
    location: 'Sagore, Pithampur',
    area: 3000,
    bedrooms: 4,
    bathrooms: 4,
    description: 'Experience luxury living in this stunning 4BHK villa. Comes with a private pool and premium fittings.',
    images: [
      'https://placehold.co/800x500.png',
      'https://placehold.co/800x500.png',
      'https://placehold.co/800x500.png',
      'https://placehold.co/800x500.png',
    ],
    amenities: ['Private Pool', 'Gym', 'Clubhouse', 'Security'],
    sellerName: 'Raj Malhotra',
    sellerPhone: '9876543215',
    featured: true,
  },
];
